//
// Created by chen on 2/17/21.
//

#ifndef WUHAN_METRO_COMMON_H
#define WUHAN_METRO_COMMON_H

#define TRUE 1
#define FALSE 0
#define ERROR -1
#define PANIC -2

#define DAY_END_TIMESTAMP 86400
#define SIX_CLOCK_TIMESTAMP 21600
#define TWENTY_THREE_CLOCK_TIMESTAMP 82800

#endif //WUHAN_METRO_COMMON_H
